---
- name: Install hibernatus dependencies
  hosts: localhost
  gather_facts: true
  roles:

  pre_tasks:
    - name: Install roles from Ansible Galaxy
      become: true
      shell: ansible-galaxy install -r requirements.yml

  roles:
   - role: geerlingguy.git
   - role: angstwad.docker_ubuntu

